apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Run after OneUptime is deployed
  name: dev-monitoring-post-boot-resize
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/nyo-infra-study/infrastructure.git
    targetRevision: main
    path: platform/monitoring/post-boot-resize
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
