# ArgoCD Self-Management
# This makes ArgoCD manage its own installation using the Helm chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: argocd
  namespace: argocd
  labels:
    environment: dev
    domain: platform
spec:
  project: default

  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 9.5.11
      helm:
        valueFiles:
          - $values/platform/argocd/values.yaml
    - repoURL: https://github.com/nyo-infra-study/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - kind: Secret
      name: argocd-secret


      jsonPointers:
        - /data
