apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kube-system-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: platform
spec:
  project: default
  source:
    repoURL: https://github.com/nyo-infra-study/infrastructure.git
    targetRevision: main
    path: platform
    directory:
      include: 'kube-system-network-policies.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
