# VPA Policy for Kube State Metrics
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-ksm
  namespace: monitoring
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-monitoring-ksm-kube-state-metrics
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: kube-state-metrics
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 200m
          memory: 256Mi
