# Sensor - Triggers workflow when new commits detected (polling)
# This listens to ConfigMap updates from the polling workflow

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: frontend-build-trigger
  namespace: argo
spec:
  template:
    serviceAccountName: argo

  # Dependencies - what events to listen for
  dependencies:
    - name: new-commit
      eventSourceName: github
      eventName: github-commits

  # Triggers - what to do when event happens
  triggers:
    - template:
        name: trigger-frontend-build
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: frontend-build-
                namespace: argo
              spec:
                # Use the WorkflowTemplate instead of inline definition
                workflowTemplateRef:
                  name: build-frontend-template

                # Override parameters from ConfigMap
                arguments:
                  parameters:
                    - name: environment
                      value: "dev"
                    - name: vite-api-url
                      value: "http://localhost:8080/api"
                    - name: image-tag
                      value: "latest"

          # Extract commit SHA from ConfigMap
          parameters:
            - src:
                dependencyName: new-commit
                dataKey: body.data.commit
              dest: spec.arguments.parameters.2.value
              # Use commit SHA as image tag
