# EventSource - Polls GitHub for new commits
# This actively checks GitHub API every 2 minutes for new commits

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: argo
spec:
  # No service needed for polling (no webhook endpoint)

  # Generic webhook to receive polling results
  generic:
    github-poll:
      url: ""
      config: |
        # This will be triggered by the polling workflow

  # Use resource event source to watch for ConfigMap updates
  # The polling workflow will update a ConfigMap with latest commit SHA
  resource:
    github-commits:
      namespace: argo
      group: ""
      version: v1
      resource: configmaps
      eventTypes:
        - ADD
        - UPDATE
      filter:
        labels:
          - key: app
            operation: "=="
            value: github-poller
