# EventSource - Listens to GitHub webhooks
# This receives webhook events from GitHub (push, release, etc.)

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: argo
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000

  github:
    frontend-repo:
      # Repository info
      owner: nyo-infra-study
      repository: infrastructure

      # Webhook endpoint
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: "" # Leave empty for now - you'll expose this via Ingress

      # Events to watch
      events:
        - push # On git push to any branch
        - release # On GitHub release
        - create # On tag creation

      # GitHub webhook secret (optional but recommended)
      # Create with: kubectl create secret generic github-access -n argo --from-literal=token=YOUR_GITHUB_TOKEN
      webhookSecret:
        name: github-access
        key: token

      # Insecure mode (for testing without webhook secret)
      insecure: true

      # Active mode - creates the webhook automatically in GitHub (requires token with repo access)
      active: true

      # GitHub API token for creating webhook
      apiToken:
        name: github-access
        key: token

      # Only trigger on specific branches (optional)
      # branches:
      #   - main

      # Content type
      contentType: json
