apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-event-source-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-event-source-role
  namespace: argo
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-event-source-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: github-event-source-sa
    namespace: argo
roleRef:
  kind: Role
  name: github-event-source-role
  apiGroup: rbac.authorization.k8s.io
