apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-monitoring-caretta
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # After core monitoring infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: monitoring
spec:
  project: default
  sources:
    - chart: caretta
      repoURL: https://helm.groundcover.com
      targetRevision: 0.0.16
      helm:
        releaseName: dev-monitoring-caretta
        valueFiles:
          - $values/platform/monitoring/caretta/values.yaml

    - repoURL: https://github.com/nyo-infra-study/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
