apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-for-monitoring
  labels:
    app: {{ .Release.Name }}-wait-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: wait-for-otel
        image: alpine/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Checking OTel Collector..."
          until curl -sf -o /dev/null http://dev-monitoring-otel-opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces; do 
            echo "Waiting for OTel Collector..."
            sleep 2
          done
          echo "Observability stack is READY!"
      restartPolicy: OnFailure
  backoffLimit: 10
