apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-for-monitoring
  labels:
    app: {{ .Release.Name }}-wait-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: wait-for-otel
        image: alpine/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Checking Mimir Gateway..."
          until curl -sf http://dev-monitoring-mimir-gateway.monitoring.svc.cluster.local/ready; do 
            echo "Waiting for Mimir Gateway..."
            sleep 2
          done
          echo "Observability stack is READY!"
      restartPolicy: OnFailure
  backoffLimit: 10
