apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-for-monitoring
  labels:
    app: {{ .Release.Name }}-wait-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: wait-for-otel
        image: alpine/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Checking OTel Collector at {{ .Values.env_raw.OTEL_EXPORTER_OTLP_ENDPOINT | default "http://dev-monitoring-otel:4318" }}..."
          until curl -sf -o /dev/null {{ .Values.env_raw.OTEL_EXPORTER_OTLP_ENDPOINT | replace ":4317" ":4318" }}/v1/traces; do 
            echo "Waiting for OTel Collector..."
            sleep 2
          done
          echo "Observability stack is READY!"
      restartPolicy: OnFailure
  backoffLimit: 10
