{{- if .Values.initScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-scripts
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $name, $content := .Values.initScripts }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
