apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: clickhouse
        minAllowed:
          cpu: 50m
          memory: 256Mi
        maxAllowed:
          cpu: "2"
          memory: 4Gi
