# VPA Policy for Profile Scraper (Alloy → Gigapipe)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-pyroscope
  namespace: monitoring
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: dev-pyroscope
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: alloy
        minAllowed:
          cpu: 20m
          memory: 64Mi
        controlledValues: RequestsOnly
        maxAllowed:
          cpu: 500m
          memory: 512Mi
