# ============================================================
# standalone ui-grafana configuration
# ============================================================
admin:
  existingSecret: grafana-auth
  userKey: admin-user
  passwordKey: admin-password
sidecar:
  datasources:
    enabled: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: P8E80F9AEF21F6940
        url: http://dev-monitoring-loki:3100
        access: proxy

      - name: Mimir
        type: prometheus
        uid: P1809F7CD0C75ACF3
        url: http://dev-monitoring-mimir-nginx.monitoring.svc.cluster.local/prometheus
        access: proxy
        jsonData:
          httpMethod: POST

      - name: Pyroscope
        type: grafana-pyroscope-datasource
        uid: P5DCCE374119EC439
        url: http://dev-monitoring-pyroscope.monitoring.svc.cluster.local:4040
        access: proxy

      - name: Tempo
        type: tempo
        uid: tempo
        url: http://dev-monitoring-tempo:3100
        access: proxy

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
    serve_from_sub_path: true

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - localhost
  path: /grafana
  pathType: Prefix
