# RBAC for Argo Workflows to manage ConfigMaps
# Needed for the github-poller CronWorkflow

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: argo
rules:
  # ConfigMap permissions for polling
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  # Workflow permissions
  - apiGroups: ["argoproj.io"]
    resources:
      ["workflows", "workflowtemplates", "cronworkflows", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-role
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: argo
