# VPA Policy for Blackbox Exporter
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-blackbox-exporter
  namespace: monitoring
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-monitoring-blackbox-prometheus-blackbox-exporter
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: prometheus-blackbox-exporter
        minAllowed:
          cpu: 5m
          memory: 16Mi
        controlledValues: RequestsOnly
        maxAllowed:
          cpu: 100m
          memory: 128Mi
