# VPA Policies for Dev namespace apps
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-backend-server
  namespace: dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-backend-server
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: dev-backend-server
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 300m
          memory: 256Mi
