# ArgoCD Application for Argo Events
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nyo-infra-study/infrastructure
    targetRevision: main
    path: argo-events

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
