apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/backend-db
    repoURL: https://github.com/nyo-infra-study/infrastructure
    targetRevision: main
    helm:
      releaseName: backend-db
      valuesObject:
        postgresql:
          auth:
            existingSecret: "backend-db-secret"
            secretKeys:
              adminPasswordKey: "POSTGRES_PASSWORD"
              userPasswordKey: "POSTGRES_PASSWORD"
              replicationPasswordKey: "POSTGRES_PASSWORD"
          primary:
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
          readReplicas:
            replicaCount: 2
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
