apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-monitoring-pyroscope
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: monitoring
spec:
  project: default

  sources:
    - chart: pyroscope
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.7.1
      helm:
        releaseName: dev-monitoring-pyroscope
        valueFiles:
          - $values/platform/monitoring/profiling-pyroscope/values.yaml

    - repoURL: https://github.com/nyo-infra-study/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
