apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-monitoring-mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: monitoring
spec:
  project: default

  sources:
    - chart: mimir-distributed
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.0.6
      helm:
        releaseName: dev-monitoring-mimir
        valueFiles:
          - $values/platform/monitoring/metrics-mimir/values.yaml

    - repoURL: https://github.com/nyo-infra-study/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
