apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: dev-monitoring-otel


  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: monitoring
spec:
  project: default
  sources:
    - chart: opentelemetry-collector
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.149.0
      helm:
        releaseName: dev-monitoring-otel
        valueFiles:
          - $values/platform/monitoring/common-values.yaml
          - $values/platform/monitoring/collector/values.yaml

    - repoURL: https://github.com/nyo-infra-study/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
