apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-monitoring-node-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: monitoring
spec:
  project: default
  source:
    chart: prometheus-node-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.41.0
    helm:
      releaseName: dev-monitoring-node-exporter
      valuesObject:
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
