apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: dev-monitoring-pyroscope


  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    domain: monitoring
spec:
  project: default

  sources:
    - chart: pyroscope
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.20.3
      helm:
        releaseName: dev-monitoring-pyroscope
        valueFiles:
          - $values/platform/monitoring/common-values.yaml
          - $values/platform/monitoring/profiling-pyroscope/values.yaml

    - repoURL: https://github.com/nyo-infra-study/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - ".spec.volumeClaimTemplates[]?.apiVersion"
        - ".spec.volumeClaimTemplates[]?.kind"
