apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-plg-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      valueFiles:
        - $values/platform/plg-stack/values.yaml

  # Additional source to get the values file from our git repo
  sources:
    - chart: loki-stack
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.10.2
      helm:
        valueFiles:
          - $values/platform/plg-stack/values.yaml
    - repoURL: https://github.com/nyo-infra-study/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: dev-plg-stack-loki
      jsonPointers:
        - /spec/volumeClaimTemplates
