{{- if .Values.reader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reader
  labels:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reader
spec:
  replicas: {{ .Values.reader.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gigapipe
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: reader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gigapipe
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: reader
    spec:
      containers:
        - name: gigapipe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.reader.port }}
          env:
            - name: CLICKHOUSE_SERVER
              value: {{ .Values.reader.clickhouse.server | quote }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.reader.clickhouse.port | quote }}
            - name: CLICKHOUSE_AUTH
              value: {{ .Values.reader.clickhouse.auth | quote }}
            - name: CLICKHOUSE_DB
              value: {{ .Values.reader.clickhouse.db | quote }}
            - name: MODE
              value: {{ .Values.reader.mode | quote }}
            - name: PORT
              value: {{ .Values.reader.port | quote }}
          resources:
            {{- toYaml .Values.reader.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
