{{- if .Values.readerPci.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reader-pci
  labels:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reader-pci
spec:
  replicas: {{ .Values.readerPci.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gigapipe
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: reader-pci
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gigapipe
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: reader-pci
    spec:
      containers:
        - name: gigapipe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.readerPci.port }}
          env:
            - name: CLICKHOUSE_SERVER
              value: {{ .Values.readerPci.clickhouse.server | quote }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.readerPci.clickhouse.port | quote }}
            - name: CLICKHOUSE_AUTH
              value: {{ .Values.readerPci.clickhouse.auth | quote }}
            - name: CLICKHOUSE_DB
              value: {{ .Values.readerPci.clickhouse.db | quote }}
            - name: MODE
              value: {{ .Values.readerPci.mode | quote }}
            - name: PORT
              value: {{ .Values.readerPci.port | quote }}
          resources:
            {{- toYaml .Values.readerPci.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
---
{{- if .Values.readerNonpci.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reader-nonpci
  labels:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reader-nonpci
spec:
  replicas: {{ .Values.readerNonpci.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gigapipe
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: reader-nonpci
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gigapipe
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: reader-nonpci
    spec:
      containers:
        - name: gigapipe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.readerNonpci.port }}
          env:
            - name: CLICKHOUSE_SERVER
              value: {{ .Values.readerNonpci.clickhouse.server | quote }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.readerNonpci.clickhouse.port | quote }}
            - name: CLICKHOUSE_AUTH
              value: {{ .Values.readerNonpci.clickhouse.auth | quote }}
            - name: CLICKHOUSE_DB
              value: {{ .Values.readerNonpci.clickhouse.db | quote }}
            - name: MODE
              value: {{ .Values.readerNonpci.mode | quote }}
            - name: PORT
              value: {{ .Values.readerNonpci.port | quote }}
          resources:
            {{- toYaml .Values.readerNonpci.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
