{{- if .Values.writer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-writer
  labels:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: writer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.writer.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: writer
---
{{- end }}
{{- if .Values.readerPci.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reader-pci
  labels:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reader-pci
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.readerPci.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reader-pci
---
{{- end }}
{{- if .Values.readerNonpci.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reader-nonpci
  labels:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reader-nonpci
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.readerNonpci.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reader-nonpci
{{- end }}
